### ISSUE TITLE
No Sound Output Device

### ISSUE THREAD

**Issue by TCB13** [frostyviking/HP-EliteDesk-800-G2-OC#3]
Hello!

I've successfully installed Monterey by following this guide. Also moved the EFI folder from the USB flash drive to the internal EFI partition and I've it booting without USB all working fine.

Unfortunately audio doesn't work. System Preferences says there's no input/output device and in System Report there isn't any device as well.

How can I debug this / what can I do?

Thank you.

**Comment by TCB13** [comment]
Here is the full info on my machine:

HP EliteDesk 800 G2 DM 65W
Processor: Intel(R) Core(TM) i5-6500 CPU @3.20GHZ
Memory Size: 8192 MB
System BIOS: N21 Ver. 02.53 04/16/2021

Audio is Realtek ALC221, same as yours.

Different CPU, BIOS from the same day but some higher revision.

**Comment by frostyviking** [comment]
Hi!
I dont have this machine onhand anymore -so i cant test or build on it.
But.. ill take a guess,

Make sure you upgrade to the latest OpenCore build including all kext's.

In the config.plist;
DeviceProperties -> Add -> PciRoot(0x0)/Pci(0x1F,0x3) <- Remove this including any children.

Then

NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args

Original Value: igfxonln=1 agdpmod=pikera keepsyms=1 debug=0x100 rtcfx_exclude=58-59,B0-B3,D0-DF

Edit to insert "alcid=##"and test another layoutid that matches the Codec ALC221.
Looking at the supported codecs -there are two different hardware revisions for this codec.
Available layout id's are 11, 15, 88

Like so: alcid=11 igfxonln=1 agdpmod=pikera keepsyms=1 debug=0x100 rtcfx_exclude=58-59,B0-B3,D0-DF

And remeber to ALWAYS have a working bootable backup EFI on USB incase anyhing goes bad.
I cant stress this enough.. =)

**Comment by TCB13** [comment]
Hi @frostyviking thank you for the tips, I was also reading https://dortania.github.io/OpenCore-Post-Install/universal/audio.html this when you posted your comment.

Now I've tried all layouts (change the value, save, reboot, change to next...) and it still doesn't work.

They also say `kextstat | grep -E "AppleHDA|AppleALC|Lilu"` should report the 3 ones, but in my case AppleHDA doesn't show up, any ideas?

Upgraded to OpenCore 0.8.1!

Thank you.

**Comment by frostyviking** [comment]
Hm.. strange,
That would indicate that AppleHDA.kext does not load or maybe outright missing from /System/Library/Extensions.
Is this installation done with latest Monterey directly or upgraded from BigSur (they way i did it before)?

Monterey is known to do spooky things, thats for sure.

**Comment by TCB13** [comment]
Well.. I'm sorry for wasting your time. This is why it wasn't working:

![Screenshot 2022-06-06 200738](https://user-images.githubusercontent.com/6315832/172229988-a6782302-d238-42c7-bb67-4c25a9b041fd.png)

I feel ashamed. Back to your original config using the layout 88.

Just for the record this was a clean installation directly with the latest Monterey burned to a flash drive. Everything is working fine now under OpenCore 0.8.1, except for the expected sleep issues.

Thank you!!

**Comment by frostyviking** [comment]
No worrys mate!
I was about to write -> reset bios defaults and recheck them as everything pointed to a missing device in ACPI.
But i thought to myself "naah, thats probably done already"

Awsome you got it going, happy hackintoshing!
